### ISSUE TITLE
Template has a bunch of unused dependencies

### ISSUE THREAD

**Issue by damienpontifex** [Azure/dotnet-template-azure-iot-edge-module#40] opened 2018-07-24 05:53 UTC
When creating a module, the dependencies of https://github.com/Azure/dotnet-template-azure-iot-edge-module/blob/master/content/dotnet-template-azure-iot-edge-module/CSharp/SampleModule.csproj#L14-L20 aren't used.

I can see a prior commit here https://github.com/Azure/dotnet-template-azure-iot-edge-module/commit/c408f21b0801f04e35c3d123c393b5cbec66d43d that would've used the Configuration packages, but the template doesn't now have the ConfigurationBuilder in Main that would need these. 

As a template it'd be great to just know the minimal packages needed. As of now, this seems to just be "Microsoft.Azure.Devices.Client". Could these others be removed to avoid confusion?

**Comment by konichi3** [comment] 2021-01-05 00:56
Hi 

We are triaging issues that are more than a few months old. 
If you don’t mind, can you follow the guidance below and take corresponding actions?

-	Please review that the issue reported still exists on the latest products (IoT Edge runtime, tooling, Visual Code/Studio extensions)
-	If it’s still an issue, please consider filing a new issue with following additional information 
o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

We plan to close issues that are more than 3 months old in a few weeks. Providing further information in a new issue ticket allow our team to triage the issue quickly.

Thank you for your feedback and interests.

Thank you,
Azure IoT Developer and Device team

**Comment by konichi3** [comment] 2021-01-09 00:40
Sorry the previous comment was not the right one. This is the right one and we are closing the issue now

Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:40 UTC
Labels: Obsolete
